import json
import re

raw_data = """
[FIVE] - Juan Carlos Diaz Maldonado (2019-12-26) - Increíble experiencia sobre un barco a vela en Barcelona... 3 días para sacar la certificación de PER a Motor... Ricardo es un excelente profesor y capitán! Resolvió todas las dudas y compartió sus experiencias en la mar. Personalmente me ayudo con los trámites burocráticos del trámite de la licencia Se los recomiendo.
[FIVE] - Júlia Ros Bofarull (2019-10-24) - Han sido tres intensivos días de aprendizaje. Dos días sobre el barco y otro día de radio. La verdad es que estoy estudiando y no dispongo de mucho tiempo libre, así que me ha sido muy práctico sacarme el PER en la Escuela Altair, hemos podido comprimir todas las prácticas a motor en tres días. Ricard sabe transmitir su pasión por el mar, y aprender desde la motivación siempre es más enriquecedor. He tenido mucha suerte con el grupo y gracias al clima que crea Ricard, constantemente estábamos preguntando y hablando, esto favorece a un rápido aprendizaje. ¡Gracias Ricard, gracias escuela Altair! :)
[FIVE] - Teresa Ros Bofarull (2019-10-24) - Apasionado del mar, cuando sube a su velero Ricard pasa a ser un gran marinero. Él sabe cómo transmitir amor y respeto por el mar. Atento y respetuoso, sabe comunicar lo más importante, yendo más allá de lo que sale en el examen y aportando consejos necesarios para ser un buen patrón, preparado para cualquier contratiempo. Le gusta compartir su conocimiento y enriquecerse dialogando con los alumnos. Supongo que esto es la definición de una buena lección: disfrutar escuchando, preguntando, dialogando, resolviendo problemas y aprendiendo juntos. ¡Gracias Ricard, gracias escuela Altair!
[FIVE] - Laura Camus (2019-10-23) - Durante 5 días hicimos con un compañero dos días de motor, dos días de vela y la radio. Hemos aprendido mucho. Ricard es una persona que se implica en el aprendizaje y deja que manejes desde el principio para adquirir las competencias necesarias.
[FIVE] - sergibedos (2019-10-15) - Una experiència inmillorable. L'escola ofereix tracte personalitzat i proper, facilitat per contactar i flexibilitat per trobar horaris convinguts per fer pràctiques . La dedicació del Ricard és màxima, i durant les classes no es desaprofita ni un minut. En definitiva, molt satisfet i amb ganes de tornar.
[FIVE] - Patricia Oliva (2019-10-11) - (Sin comentario)
[FIVE] - Juan Velasco (2019-05-20) - Todo genial en las practicas de ampliacion de PER en modo travesía 24h. Navegamos desde el port olímpic de Barcelona rumbo al Sur y regresamos tras fondear unas horas en Vilanova. Zarpamos con mal tiempo, olas y algo de lluvia, y aprendimos muchísimo de navegación. El viento nos permitió probar la navegación a vela. En general una experiencia fantástica y muy recomendable. El patrón Ricard lo explica todo y sobretodo deja que los alumnos prueben todo y realicen todas las maniobras.
[FIVE] - Ramon Pérez (2019-05-15) - Un auténtico profesional. Ricard me ha enseñado y atendido a todas mis dudas sobre navegación. Volvería a realizar de nuevo los cursos pertinentes con él. Es un navegante nato. Utiliza una pedagogía práctica y experimental muy adecuada al perfil de alumnado y materia que imparte.
[FIVE] - David Blanco (2019-03-28) - Necesitaba disposar de la llicència de navegació de forma rápida i a poder ser entre setmana. (la resta d'escoles ho fan els dissabtes i diumenges). Vaig trobar al Ricard, de la escola ALTAIR. Un profesional apassionat per la navegació. Va ser una experiencia exquisita, ja desde el primer moment que hi vaig contactar. I d´un dia per l´altre, ja estava fent el curs al seu fantastic veler. Personalment, recomanaría a qui tingui que realitzar formació náutica que ho fes amb el Ricard. Poder es un xic més car que altres escoles, però ho val. Ja que el tracte és totalment personalitzat i ja desde el primer moment estás pilotan l'embarcació tu mateix sota les seves indicacións. 100% Recomanable, i si m´animo a fer titulacións superiors, tinc clar que ho faré amb ell.
[FIVE] - Cecilio Postigo (2019-03-19) - Una experiencia impresionante. Muy recomendable navegar con Ricard ya que posee una barbaridad de experiencia y buenos consejos para disfrutar y aprender a navegar...
[FIVE] - Blanca Garcia (2019-03-19) - Ricard me ayudó a prepararme el examen teórico (especialmente la parte de cartas de navegación) y me proporcionó apuntes. Buena preparación para el examen en grupos reducidos (2 personas en mi caso) y siempre trata que todos lo entendamos, explicándolo de diferentes maneras si es necesario. También realicé con el las practicas donde tuvimos la ocasión de ver los problemas del examen en una situación real. Siempre crea buen ambiente entre el grupo y posibilita la participación de todos los miembros.
[FIVE] - Hernan Militello (2019-03-19) - Excelente experiencia. He realizado las prácticas de motor en dos dias, 8hs cada uno. Ricard fue el encargado de darnos las clases y no sólo hemos aprendido mucho sino que además nos lo hemos pasado muy bien. Recomendable al 100%.
[FIVE] - gerard crosa (2019-03-04) - Contacté con Ricard a través de Google. Desde un primer momento el trato ha sido excelente, persona muy profesional y afable. Después de realizar las prácticas de navegación y seguridad con él me gustaría remarcar el buen ambiente que crea, con grupos reducidos, y un trato muy cercano para que aprendas a navegar. Se nota que le gusta mucho lo que hace y lo demuestra dando las clases. Muy recomendable.
[FIVE] - Silvia Gallart Arroyo (2019-02-24) - He tenido muy buena experiencia con Ricard, crea buen ambiente, explica muy bien y se preocupa porque todos los alumnos tengamos la oportuniad de practicar todo el rato y salir con los conceptos muy claros. Hemos sido un grupo pequeño de 5 personas y ha sido perfecto porque se aprende muchisimo. Además, hemos hecho tanto navegación de día como de noche que no en todas las escuelas nauticas lo hacen. La experiencia ha sido buenisima, lo recomiendo 100 x 100.
[FIVE] - Fred Fred (2019-02-04) - Yo ya tengo el PER y sigo haciendo classes con Ricard. Tiene muchas facilidades para compartir su experiencia. Explica como se hacen las cosas, porque se hacen asi y que pasaria si no lo haces bien. Lo recomiendo a todos los que quieren repasar maniobras antes de volver a alquiler un velero!
[FIVE] - Miguel Cruz Varea (2018-12-19) - Por fechas y por la meteo pase por varias escuelas. Está la recomiendo especialmente. Ricard se involucra en lo que hace y te explica pacientemente. Ahora estoy rizando la mayor como un campeón. Gracias Ricard.
[FIVE] - Edouard (Edu) (2018-12-04) - Encontré la escuela de Ricard a través de google y me apunte sin dudarlo. Es totalmente recomendable y Ricard es un excelente Profesor. Aprendí mucho con él y me saque el PER a la primera! Ahora me tocara navegar por mi cuenta y sé que si lo necesito, Ricard siempre estará disponible para ayudarme o aconsejarme.
[FIVE] - Mariona Torrent Lluch (2018-09-29) - Vam realitzar les pràctiques d’ampliació del PER per travesia i puc dir que és totalment recomanable!!! 48h de navegació on vam aprendre i disfrutar molt del mar i de la navegació nocturna. Tot de la mà del Ricard, sempre molt atent i proper, i adaptant-se al nivell de cadascú. Una experiència molt bona, gràcies Ricard i escola Altair!!! :)
[FIVE] - Jade (2018-06-10) - Un excelente profesional, un curso muy didáctico y ameno. Lo recomiendo 100%.
[FIVE] - Alejandro Blanco (2018-06-08) - Esta semana cursé la Licencia de Navegación en la Escuela Náutica Altair, he de decir que la experiencia ha superado todas mis expectativas. Tanto por la organización previa como por el desarrollo de la clase con Ricard -una persona experimentada y muy didáctica-. Por si fuera poco en solo en 3 días recibí la licencia!!! Repetiría sin dudarlo.
[FIVE] - carles santacreu i manuel (2017-07-19) - Una bona experiència amb un bon formador que sap explicar de manera senzilla tot el que s'ha d'aprendre.
[FIVE] - nric (2017-07-18) - Escuela nautica altamente recomendable, tanto si ya tienes experiencia como si es tu primera vez (como fue mi caso) disfrutarás de la sensación de navegar en manos de un gran profesional como Ricard, apasionado del mar y con mucha capacidad para transmitir conocimientos a sus alumnos. Calidad precio inmejorable, la nautica al alcance de todos.
[FIVE] - Guillem Ferrer (2017-07-12) - Ens hem tret la llicencia de navegacio amb en ricard i ha estat un dia genial amb una mica de teoria dins del veler i despres practica navegant fins a badalona,fins i tot vam anar un rato a vela!una experiencia genial! En ricard es un gran profe i explica molt be les coses,si algun dia em vui treure el de patro tornare.
[FIVE] - Gipsy Moth IV (2017-06-30) - Gran dia a bordo del altair!! Salida con gran actividad didactica con ratos de esparcimiento y conversa. Gran experiencia!!
[FOUR] - Marta Ribas (2017-06-29) - (Sin comentario)
[FIVE] - Anna (2017-06-09) - M'he tret la llicència de navegació i ha sigut una experiència molt bona. Hem fet dues hores de teoria dins del vaixell i després hem sortit a navegar unes 4h. En Ricard (el profe) ho explica tot molt bé i et fa passar una bona estona. Si algun dia em vull treure un altre títol més avançat segur que torno a Altair :)
[FIVE] - Ignasi Sol Puig (2017-06-12) - Ha sido una experiencia genial. 24h navegando con un experto se aprende mucho. Capitan muy experto y con paciencia para dar explicaciones de todo a todos. 100% recomendable.
[FIVE] - Alex Egea de la Varga (2017-06-08) - He quedado muy contento por la gran profesionalidad, simpatia y mucha seguridad navegando!!!
[FIVE] - Edu Egea (2017-06-05) - Pasamos una mañana genial! 100% recomendable, muy profesional y muy ágil con todos los trámites, Gràcies Ricard!
[FIVE] - Antoni Rosell Mele (2017-05-31) - Excelente práctica de navegación de ampliación del PER con Ricard. Es un instructor que da mucha confianza, es práctico, paciente y eficaz en resolver dudas y sabe mucho. Su velero Hunter es una joya, y amplio y cómodo para ir en grupo.
[FIVE] - Andrea Prehn (2017-05-26) - Genial!
[FIVE] - To Rie (2021-11-29) - Great experience!
[FIVE] - P L (2021-11-29) - Mi experiencia con Ricard ha sido genial. He tenido el placer de preparar el PER con el y de aprender muchisimas cosas que avivan aún más mis ganas de seguir navegando. Es capaz de transmitir su pasión por el mar y hacer que los alumnos formen parte activa de ello. Sin duda recomiendo la escuela náutica Altair a cualquier persona que tenga interés de aprender del mejor! Gracias por todo Ricard
[FIVE] - Jane Stackhouse (2021-09-09) - Ricard is an excellent teacher. I have 16 years experience as a corporate trainer for Nike. I can assure you that you will be able to use your new knowledge and skills immediately. I rate Ricard an ‘excels’ for his instructional skills, sailing knowledge, and patience.
[FIVE] - Stephanie Frendo (2021-07-28) - Una experiencia fantastica por las 48h de navigacion. Muy muy recomandable! Securidad, profesionalismo y passion, todo reunido para aprender a lo maximum. Les 48h de navigation furent une experience fantastique! Ultra recommandable! Securite , professionnalisme, passion , tout reunis dans cette experience pour bien apprendre et profiter.
[FIVE] - manu caballero (2021-07-14) - Buenas tardes, hoy he efectuado las prácticas de la Licencia de Navegación durante la mañana, y me he quedado sorprendido por la gran eficacia y el gran aprendizaje obtenido , por el instructor sr. RICARD. Gran profesional, y gran persona, que no duda en ningún momento en ayudar, y enseñar. Lo dicho, gran experiencia gracias a SR. RICARD, y muy buen instructor. le Felicito. gracias.
[FIVE] - Flavia Nanzer (2021-06-26) - Hace una semana estaba haciendo las prácticas para ampliar atribuciones del PER a Baleares y hoy estoy estamos fondeados en Illa de Colom en Menorca... Todo muuuy bien... Muchas gracias, Ricard!
[FIVE] - Joan Ferrer (2021-06-21) - Salida extensión PER baleares con Ricard, ha sido toda una experiencia, se nota que es un navegante con más de 20 años de experiencia además de apasionado de la navegación. Con el no solo refrescas y te actualizas en la navegación, su contagiante obsesión por la seguridad y el conocimiento de los peligros, ratifica que navegar es un placer pero que la seguridad no es baladí. Además Ricard en toda la navegación comparte su experiencia y conocimiento de la navegación con soluciones a problemas y situaciones que son muy útiles más allá de lo que son los conceptos académicos del curso. Para los que ya tienen experiencia se sorprenderán de lo que pueden aprender en estas intensas 24 horas.
[FIVE] - Joaquim Triginer (2021-06-17) - Una experiència fantàstica fer el curs de la Llicència de Navegació amb el veler Certescan de la vostra escola. Les bones explicacions de'n Ricard, molt intel·ligibles i instructives i el practicar-ho tot in situ, varen fer que l'aprofitament per part meva fos total. Recomano la vostra escola per a tot tipus de llicències. Jo en vaig quedar molt content.
[FIVE] - Mathilde GODET (2021-06-11) - Ricard es un profesional. Le apasiona lo que hace y está deseoso de compartir sus conocimientos. ¡Sólo puedo recomendarlo! Los otros estudiantes son muy agradables. Ven a sacarte tu licencia de navegación, PER y PNB en la Escuela Náutica Altair !!
[FIVE] - Alex Buxó (2021-05-12) - Excelente. Con Ricard te sacas más que un título. Las prácticas son toda una experiencia en su velero y se esfuerza en que tengas travesías extraordinarias. Además te enseña a navegar y realmente te prepara para salir como capitán. Se nota su gran experiencia. Pedidle que os cuente historias!!
[FIVE] - ELAFINADORDEPIANOS (2021-05-08) - Una buena experiencia marina para aprender a navegar! Buenos consejos de un maestro experto . Gracias Ricard!
[FIVE] - CARLOS OLIVAN DE ALLER (2021-04-16) - Altair, se caracteriza por su profesionalidad, seriedad y efectividad, Ricard, el docente principal, el te enseña, te ayuda, hace hincapié, hasta que te ve que dominas, fantástico con la teórica y la práctica...En resumen, no tengo ninguna duda de aconsejar LA ESCUELA NAUTICA ALTAIR...⛵️
[FIVE] - miquel seriola (2021-04-13) - Recomendado para personas que quieran iniciarse al mar. El trato de Ricard, muy profesional y entendible. Grandiosa paciencia con los alumnos, incansable a la hora de exponer cada tema.
[FIVE] - Nilo Duran García (2021-04-13) - (Sin comentario)
[FIVE] - David roux (2021-04-12) - Aprendí mucho con Ricard. Clases muy profesionales y informativas. Merci
[FIVE] - Begonya Sarrias (2021-02-08) - Excel.lents explicacions didàctiques per poguer resoldre aspectes de forma autònoma i no mimètica Capacitat per crear l’ambient adient per pensar i passar ho bé Molt recomanable ! Gràcies Ricard
[FIVE] - Marcos Perez mallada (2021-01-20) - Gran actividad!! Muy divertido el profe un maquina!!!😊😊😊
[FIVE] - Axel Gil (2021-01-17) - Fantàstica experiència, tracte i dedicació! Molt recomanable amb un tracte molt proper, personal i professional. Simplement genial!
[FIVE] - PAULO Pinto (2021-01-04) - (Sin comentario)
[FIVE] - Andres Meoli (2020-12-09) - Recomiendo 100% a Ricard y la escuela, muy buen profesional, con mucha paciencia y cooperacion constante. Yo he realizado las practicas para el PER con la escuela y no teno ninguna queja.
[FIVE] - Lucas Ciocca (2025-03-17) - Ya he realizados dos cursos con Ricard, la verdad que un crack. Enseña muy bien todos sus conocimientos. Lo recomiendo 100% !!!
[FIVE] - Gendri Vernici (2024-12-05) - Noooo, si vierais la calidez, la responsabilidad y los conocimientos que transmite Ricard a la hora de instruir; en lo personal puedo garantizar la enseñanza y el conocimiento técnico adquirido en esta escuela, tanto que la recomiendo para futuras formaciones, aprendizajes técnicos y asesorías. Respectivamente cada servicio profesional que ofrece, será una puerta a un mundo diferente y que sobre todo esta inmerso en posibilidades que al final producen una satisfacción absoluta. Tenéis que venir cuanto antes. ¡Apuntaros!
[FIVE] - Odi Bazó (2025-02-08) - Ricard ha sido un gran profesor, muy paciente y sabe de todo. lo recomiendo mucho. Ricard has been a great teacher, very patient and knows everything. I highly recommend him.
[FIVE] - Andrés Navarro (2024-12-20) - Es mereix un 10 per ser un gran professional expert en la matèria i que fa que els cursos impartits siguin molt amens.
[FIVE] - Alexandra fernández (2024-12-07) - Hice el curso de licencia de navegación y me encantó. El instructor explicó todo súper bien, tanto la teoría como la práctica. En el barco, pude tomar el timón y aprender a hacer maniobras básicas; fue emocionante sentir el control y cómo responde la embarcación. La práctica fue divertida y muy entretenida, lo disfruté muchísimo. Sin duda, volveré para seguir practicando con ellos. Añadir
[FIVE] - Giomar Alexandra Fernández Pabon (2024-12-06) - Hice el curso de licencia de navegación y me encantó. El instructor explicó todo súper bien, tanto la teoría como la práctica. En el barco, pude tomar el timón y aprender a hacer maniobras básicas; fue emocionante sentir el control y cómo responde la embarcación. La práctica fue dinámica, divertida y muy entretenida, lo disfruté muchísimo. Sin duda, volveré para seguir practicando con ellos. ☺️
[FIVE] - David Lázaro Lavilla (2024-12-06) - Amb el capità Ricard Prehn vam tenir una gran jornada molt bonica d'aprenentatge, va ser ràpid, instructiu, tots vam poder maniobrar i conduir una estona. També va ser divertit. L'aprenentatge dels nusos va ser molt bén donat. I se'ns va transmetre breument però principalment la informació d'una carta nautica. Tot realitzant-se insitu al vaixell, de manera intensiva. Això va ser una manera molt interessant de treure's la titulació més que accedir a una aula assegut i després fer la pràctica, aquí estaves a l'embarcació en moviment en tot moment. Se'ns va ensenyar a fer previsió del temps amb una aplicació, el funcionament de sortida i entrada dels ports, amarrar, aparcar, etc. I també se'ns va instruir amb els modus de salvament que hi han al vaixell. Fins i tot vam fer un café, com a extra! Va ser tot molt agradable.
[FIVE] - Yesi Fernandez (2024-12-06) - Realicé el curso de licencia de navegación con Ricard, y fue una experiencia increíble. Explicó todo de manera muy detallada, asegurándose de que entendiéramos cada concepto antes de avanzar. Fueron 6 horas bien aprovechadas, combinando teoría e información práctica que hicieron el aprendizaje muy dinámico y claro. Además, la práctica fue muy entretenida y útil, Lo recomiendo totalmente a quienes quieran iniciarse en el mundo de la navegación!
[FIVE] - Ale Ale (2024-12-04) - (Sin comentario)
[FIVE] - Caetano Papirblat (2024-11-18) - Recomendado 100%, fue una mañana de puro aprendizaje, sin hacerse repetitivo o tedioso, Ricard es un gran instructor y profesional y te transmite su pasión por el mar y la navegación!
[FIVE] - Javier Calvo (2024-11-29) - La Escuela Nautica Altair es sin duda alguna la mejor opción para aprender a navegar a vela. Ricard es un gran maestro, bien sabedor del oficio te enseñará lo necesario y mucho más para agarrar confianza. Aplica una metodología de enseñanza en donde rápidamente estás haciendo las cosas tu mismo bajo su supervisión lo que te anima a querer saber y hacer más. Es una escuela flexible en temas de horarios y muy buenos precios. Regreso cada año a repasar y seguir aprendiendo. Ciento por ciento recomendados.
[FIVE] - Javier mohedano reus (2024-11-28) - Vaig fer el curs de maneig d'embarcacions de salvament en platja i la llicència de navegació. Gran professional en Ricard. Va ser una gran experiència. Un dia amb amics. Moltes gràcies als nois de salvament marítim i a tu Ricard. Molt recomanable.
[FIVE] - Melisa Montero (2024-11-28) - Hice el curso para la Licencia de navegación básica con Ricard, hubo parte teórica y parte práctica, todo muy bien explicado. Además la parte de los trámites super expeditiva, en dos semanas ya tenía todo! El curso contsta de media jornada donde se realizan nudos básicos, salida del puerto, se hacen varias prácticas de “estacionamiento”, y nos explica las diferentes aplicaciones para ver estado de variables náuticas básicas para un viaje seguro y ameno. Seguramente haremos algunas prácticas más! Mi objetivo era poder alquilar barcos pequeños recreativos principalmente en vacaciones y con esto me siento mucho más segura para hacerlo!! 🛥️
[FIVE] - Alexis Ramon Casado (2024-11-22) - Fui el día 20 de noviembre de este 2024 con Ricart, el patrón del velero, y la verdad resultó todo mucho más y mejor de lo que esperaba! Hace las clases muy bien, explica muy bien y se aprende con él muy bien. La navegación es increíble, y puedes hacer de todo, llevar el timón, arriar velas, amarrar el velero, de todo. Y siempre con las explicaciones de Ricart sobretodo lo que vamos haciendo. Es de diez, yo iría otra vez, y otra y otra y otra...
[FIVE] - Lili (2024-11-22) - Siempre me ha fascinado el mar, y ahora con ganas de navegar por mí misma. En este curso de 1ra licencia, aunque muy compactado, aprendes lo básico, en teoría y práctica, porque Ricard te deja al mando y trasmite sus conocimientos con mucha experiencia y pasión. Totalmente recomendable, y por supuesto pasar al siguiente nivel.
[FOUR] - Cristian Micale (2024-11-19) - Muy buena la capacitación, recomendable 100 x 100!!
[FIVE] - Alejandro Muñoz Alcalá (2024-11-12) - Me encantó realizar el curso de licencia de navegación. Todo el contenido se hizo súper ameno e interesante, además de una formación muy completa para sentirme seguro a la hora de salir a navegar. Ricard, el instructor fue muy atento y lo puso todo muy fácil. 100% recomendado.
[FIVE] - Carlos Fabian (2024-11-06) - Muy buen profesor! , con clases teóricas prácticas navegando.
[FIVE] - S.R. (2024-10-29) - Recomiendo mucho esta escuela para obtener cualquier licencia. La formación por parte de Ricard realmente se hace muy amena y entretenida. Aprendes mucho en poco tiempo y pasándotelo muy bien. Se genera muy buen ambiente y tod@s hacemos de todo para poder tener feedback, mejorar y aprender bien. Me quedo con ganas de meterme más en el mundillo así que repetiré en esta escuela para seguir ampliando conocimientos.
[FIVE] - Stanley Macias Rizzo (2024-10-22) - Una experiencia única, navegar con la enseñanza y prácticas que da el instructor , es de 10, lo recomiendo, profesor atento y te enseña con carisma y respeto , gracias profe.
[FIVE] - Edu Real (2020-12-08) - Ricard, el dueño me recomendó hacer el PER con extension a Baleares y la verdad es que fue una excelente idea. Gran experiencia, aprendimos un montón y conocí a gente nueva e hicimos un grupo muy majo. El barco tiene de todo, esta limpio, ordenado y da sensación de seguridad. En la travesía lo que más me sorprendió fue la paz y tranquilidad, y tanto el amanecer como la noche bajo las estrellas son impagables.
[FIVE] - Albert Naudin (2020-11-04) - Curs molt útil per navegar amb seguretat, pràctiques molt personalitzades en fantàstic veler. Molt recomanable!
[FIVE] - Renato Miralla (2020-10-19) - Fizemos as práticas de travessia de 48 horas para PER com Ricard (Escuela Altair) e foi uma experiência fantástica. Travessia segura, muito aprendizado e um grupo de pessoas muito legal. Ricard é uma pessoa que tem muito conhecimento e faz questão de explicar tudo de maneira descomplicada e clara. Além da travessia em si, aproveitamos nosso tempo para fazer inúmeras manobras no veleiro, conhecer muito bem o funcionamento das velas, cabos, instrumentos e regras de navegação...enfim, uma experiência muito completa e prazerosa. Muchas gracias Ricard e recomendo a todos que queiram a aprender a navegar em Barcelona!
[FIVE] - Joaquim Just (2020-09-28) - Hicimos el curso para la licencia de navegación con Ricard y fué de nivel excelente la experiencia.
[FIVE] - Fran Mosteiro (2020-09-12) - Experiencia muy recomendable. Invertir la mañana de sábado con Ricard y algunas compañeras más, aprendiendo algunos de los secretos detrás de la navegación: obligatoriedades, maniobras básicas, fondeo, atraque, etc como parte del aprendizaje para obtener la Licencia de Navegación, sin duda, ha merecido la pena :) Una maravillosa experiencia, una magnífica manera de aprender a navegar y, sin ninguna duda, un gran maestro y una excelente “aula”, el Certascan. Gracias a ambos!
[FIVE] - Eduardo J. Celorio (2020-08-27) - Hice el curso con Ricard por un par de recomendaciones entusiastas y ahora soy yo quien os lo recomienda. Se lo toma con la profesionalidad que hay que hacerlo pero además, lo pasas muy bien. Lo recomiendo ampliamente.
[FIVE] - Laura (2020-07-25) - He hecho las prácticas del PER con Ricard y la verdad es que es un muy buen instructor, aprendimos mucho y la experiencia fue muy buena! Ricard ha sido accesible en todo momento resolviéndonos dudas via whatsapp los dias antes del examen! Sin duda recomiendo la escuela náutica Altair!
[FIVE] - Sonia Ferreiro (2020-07-25) - Una experiencia genial! Pudimos realizar las prácticas del PER los cuatro hermanos juntos en pocos días y aprendiendo mucho. Ricard ha sido un excelente profesor! Escuela Náutica Altair es, sin duda, muy recomendable!!
[FIVE] - w w (2020-07-25) - Alegria mariners! Ricard gran professional una experiència molt positiva s aprèn molt per a tots/es els que vulgueu aprendre a navegar us ho recomano!
[FIVE] - Joan Carles Cifre (2020-07-20) - El Ricard d'Altair m'ha ofert una molt bona experiència de contacte amb la Navegació, molt personalitzada i atenta amb tots els detalls, desde el procés d'inscripció i tràmits administratius fins a l'aprenenentatge a bord del seu veler. He disfrutat aprenent i navegant amb ell i compartint la seva pasió. Ja tinc ganes de treure'm el proper títol!
[FIVE] - Seti (2020-07-19) - En Ricard sempre està disponible per els dubtes que poguin sorgir. Han estat unes pràctiques molt divertides, i la teoria es fa amena amb regles memotècniques. Moltes gracies!!
[FIVE] - Luis Rosúa (2020-07-19) - Vaig treure'm la llicència de navegació. L'experiència va ser molt positiva i enriquidora, en Ricard és un gran professional i amb molts coneixements sobre navegació. Va estar molt atent del grup i va explicar-nos el contingut del curs de manera amena i fàcil d'entendre. Una vegada a mar obert, entre altres coses, ens va parlar del funcionamet dels instruments de navegació, demostrant un gran coneixement d'aquests i del mar en general, a destacar també la seva preocupació per si ens marejavem. Tant a nivell professional com a nivell humà recomano fer la formació sobre navegació amb l'escola Altair, Lluís
[FIVE] - Brian C. (2020-07-13) - Hicimos el curso para la Licencia de Navegación y la verdad fue todo excelente. Buen grupo, reducido, y Ricard explica muy bien y responde todas las preguntas con claridad y paciencia. Durante el tiempo de práctica vamos rotando las posiciones y tareas en la embarcación, por lo que haces de todo. Definitivamente recomiendo el curso. Ahora veremos si me animo a hacer el PNB :) Gracias Ricard!
[FIVE] - V Wei (2020-07-12) - (Sin comentario)
[FIVE] - Miuq Mi (2020-07-06) - Fui desde Gerona para realizar las 48 horas de vela+Baleares y fue una experiencia inolvidable. Tuve la suerte de embarcarme con un espléndido grupo y aprender disfrutando de los conocimientos de Ricard que es un gran maestro de la náutica. Recomendable 100%
[FIVE] - Marc Basolí (2020-06-30) - Recomiendo mucho a esta escuela náutica donde he podido gozar de la experiencia de Ricard el profesor y dónde además de sacarme el PER entero, he podido gozar de un fin de semana en Mallorca como si de vacaciones se tratara. El velero y la navegación ha sido fantástico.
[FIVE] - ORIOL VILAR (2020-06-18) - (Sin comentario)
[FIVE] - Filippo Di Remigio (2020-03-22) - Awesome experience. Had great time with Ricard and the other participants. Highly recommended.
[FIVE] - J. Leyton (2020-03-11) - Una experiencia increible. Fuimos a realizar las practicas del PER en modo intensivo y en 5 días obtuvimos las atribuciones de vela, baleares, prácticas de radio y de seguridad. Desde el primer momento Ricard te pone a los mandos del Certascan, entradas y salidas de puerto, amarres, fondeos, navegación nocturna, en muchas ocasiones tu decides la derrota. Te enseña un buen marinero.
[FIVE] - Mary (2020-03-06) - La experiencia fue increíble. Desde el primer minuto Ricard nos dejó manejar a vela y a motor así como hacer numerosas maniobras dentro de puerto, aunque en todo momento te sientes respaldado por su experiencia y conocimiento del mar. No solo aprendes sino que también resulta una experiencia divertida y motivadora. Sobre el profe ya está todo dicho :D amable, divertido, motivador y siempre atento para resolver tus dudas antes, durante e incluso después del curso. En cuanto al barco resultó cómodo y bien equipado tecnológicamente. En mi caso hice el curso del PER con atribución de vela y ampliación a Baleares. Para la parte de seguridad y radio, su escuela también cuenta con equipos de simulación. En resumen, muy recomendable. Gracias por todo Ricard!
"""

reviews = []
lines = raw_data.strip().split('\n')
for line in lines:
    line = line.strip()
    if not line: continue
    
    # Regex to parse: [RATING] - Name (Date) - Comment
    match = re.match(r'^\[(FIVE|FOUR|THREE|TWO|ONE)\] - (.*?) \((.*?)\) - (.*)$', line)
    if match:
        rating_str, name, date, text = match.groups()
        
        # Convert rating
        rating_map = {
            'FIVE': 5,
            'FOUR': 4,
            'THREE': 3,
            'TWO': 2,
            'ONE': 1
        }
        rating = rating_map.get(rating_str, 5)
        
        # Clean text
        if text == "(Sin comentario)":
            continue # Skip empty reviews? Or keep them? User said "feed the reviews". 
                     # Reviews with no text are boring for testimonials. Let's skip them.
        
        reviews.append({
            "name": name,
            "text": text,
            "rating": rating,
            "date": date
        })

# Output JSON
print(json.dumps(reviews, indent=4, ensure_ascii=False))
